sudo: false
language: python
python:
- '2.7'
- '3.2'
env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9,<1.10'
install:
- pip install -q Django$DJANGO_VERSION
- python setup.py -q install
script: python setup.py test
# Report to coveralls
after_success:
  - coveralls